#### Word Embedding

In [13]:
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [15]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
## Define the vocabulary size
voc_size=10000

In [17]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3042, 9049, 3304, 700],
 [3042, 9049, 3304, 6818],
 [3042, 758, 3304, 3277],
 [8954, 7577, 8350, 7468, 5666],
 [8954, 7577, 8350, 7468, 6965],
 [7017, 3042, 1723, 3304, 2095],
 [8674, 4612, 1383, 7468]]

In [19]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np

In [21]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3042 9049 3304  700]
 [   0    0    0    0 3042 9049 3304 6818]
 [   0    0    0    0 3042  758 3304 3277]
 [   0    0    0 8954 7577 8350 7468 5666]
 [   0    0    0 8954 7577 8350 7468 6965]
 [   0    0    0 7017 3042 1723 3304 2095]
 [   0    0    0    0 8674 4612 1383 7468]]


In [22]:
## feature representation
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step


array([[[ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [-0.04072801, -0.01912954,  0.00346011,  0.00925971,
         -0.03138832, -0.00470068, -0.04055243,  0.02516904,
         -0.02597741, -0.04688703],
        [ 0.01503303, -0.03400451,  0.00294923,  0.02835644,
          0.02447278, -0.02758797, -0.02951964,  0.04265771,
          0.00448991, -0.01057253],
        [ 0.02841547,  0.04534164, -0.03473445,  0.0

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0, 3042, 9049, 3304,  700])

In [28]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[[ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [ 0.01361897, -0.00579137, -0.04271723,  0.00443827,
         -0.04229856,  0.02886363,  0.04537762,  0.03058663,
          0.02972856,  0.00546841],
        [-0.04072801, -0.01912954,  0.00346011,  0.00925971,
         -0.03138832, -0.00470068, -0.04055243,  0.02516904,
         -0.02597741, -0.04688703],
        [ 0.01503303, -0.03400451,  0.00294923,  0.02835644,
          0.02447278, -0.02758797, -0.02951964,  0.04265771,
          0.00448991, -0.01057253],
        [ 0.02841547,  0.04534164, -0.03473445,  0.0