# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
import numpy as np

array = np.random.randint(1,21,size = (5,5))
print("Original Array")
print(array)

array[:,2]=1
print("Modified Array")
print(array)



Original Array
[[17 19  8 13  4]
 [16 20 14 15 15]
 [ 8  8  3 20 19]
 [12 11  5  3 14]
 [ 1  1 14 15 11]]
Modified Array
[[17 19  1 13  4]
 [16 20  1 15 15]
 [ 8  8  1 20 19]
 [12 11  1  3 14]
 [ 1  1  1 15 11]]


This code snippet is modifying a NumPy array by replacing all elements in the third column with `1`. Let's break it down step by step:

### Explanation:

1. **`array[:, 2] = 1`**  
   - `array` is assumed to be a NumPy array.
   - `:` in `array[:, 2]` means **"select all rows"**.
   - `2` in `array[:, 2]` refers to the **third column** (indexing starts from 0).
   - `= 1` sets all values in this column to `1`.

2. **`print("Modified array:")`**  
   - Displays the message `"Modified array:"` before printing the updated array.

3. **`print(array)`**  
   - Prints the modified array to the console.

### Example:

#### Before Modification:
```python
import numpy as np

array = np.array([[5, 8, 3], 
                  [2, 6, 9], 
                  [4, 7, 5]])

print("Original array:")
print(array)
```
**Output:**
```
Original array:
[[5 8 3]
 [2 6 9]
 [4 7 5]]
```

#### After Modification:
```python
array[:, 2] = 1  # Replacing third column with 1
print("Modified array:")
print(array)
```
**Output:**
```
Modified array:
[[5 8 1]
 [2 6 1]
 [4 7 1]]
```

### Key Takeaways:
- The slicing operation `array[:, 2]` selects the entire third column.
- Assigning `1` to `array[:, 2]` updates all elements in that column.
- Useful for modifying specific columns in multi-dimensional arrays.

In [6]:
array = np.arange(1,17).reshape((4,4))
print("Original Array")
print(array)
print(" \n")

np.fill_diagonal(array,0)
print("Modified Array")
print(array)


Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 

Modified Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [9]:
array = np.arange(1,37).reshape(6,6)
print("Orriginal Array")
print(array)
print(" \n")

sub_array = array[2:5,1:4]
print("Sub Array:")
print(sub_array)

Orriginal Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
 

Sub Array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [11]:
array = np.random.randint(1,26,size = (5,5))
print("Original Array")
print(array)
print("\n")

border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original Array
[[ 6 14 12 17  6]
 [21 18 15  1 20]
 [22  2 25 18 18]
 [ 6 18 15  8 14]
 [ 3  6  8  4  1]]


Border elements:
[ 6 14 12 17  6  3  6  8  4  1 21 22  6 20 18 14]


### **`array[1:-1, 0]` Ka Matlab Kya Hai?**  

👉 **Yeh ek NumPy slicing operation hai jo array ke left border ke middle elements ko extract karta hai.**  
Matlab **first row aur last row ko chhodke, sirf beech ke rows ka first column select karega.**  

---

### **Example Code (Step-by-Step)**  
```python
import numpy as np

# 5x5 ka random integer array (1 se 20 ke beech)
array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:")
print(array)

# Border elements nikalna
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))

print("\nBorder Elements:")
print(border_elements)
```

#### **Maan lo, randomly generate hua array yeh hai:**
```
[[ 8  2 14  7  6]
 [19 12  3 18  5]
 [13 11  9  1 17]
 [10 20  4  8 16]
 [15  6 10 19 14]]
```

---

### **Understanding `array[1:-1, 0]`**  
👉 Yeh **"middle rows ke first column"** ko select karega.  

#### **Step-by-Step Breakdown:**
- **`1:-1` → Row selection:**  
  - Yeh **first (0th) aur last (-1th) row ko exclude karega.**
  - Sirf **1st row se lekar (n-2)th row tak ka data milega.**
  
- **`, 0` → Column selection:**  
  - Yeh **first column (index `0`) ko select karega.**

#### **Selected Elements:**
- **Original Array:**  
  ```
  [[ 8  2 14  7  6]  → (0th row) ❌ Ignore
   [19 12  3 18  5]  → (1st row) ✅ Include
   [13 11  9  1 17]  → (2nd row) ✅ Include
   [10 20  4  8 16]  → (3rd row) ✅ Include
   [15  6 10 19 14]] → (4th row) ❌ Ignore
  ```
- **Result (`array[1:-1, 0]`):**
  ```
  [19 13 10]
  ```

---

### **Final Output of `border_elements`:**
Yeh **saare border wale elements extract karega**, including **top row, bottom row, left border ke middle elements, aur right border ke middle elements**.  

🔹 **Border elements (`border_elements`):**
```
[ 8  2 14  7  6  15  6 10 19 14  19 13 10  5 17 16]
```
---

### **TL;DR (Short Summary)**
👉 **`array[1:-1, 0]` ka matlab hai:**
- **First aur last row ko hata ke beech ke rows ka first column select karna.**
- **Agar `5x5` ka array hai, toh yeh `3` elements return karega (`1st`, `2nd`, aur `3rd` row ka 1st column).**  
- **Iska use border extraction ya specific column ke elements nikalne ke liye hota hai.**  

---

🔥 **Agar samajh aaya toh likho "NumPy Slicing OP!" 😃**

In [4]:

import numpy as np
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 6  9  5  6]
 [10  9  3 10]
 [ 4  3  1  4]]
Array 2:
[[ 9  1  5 10]
 [ 5 10  1  2]
 [ 9  3  7  8]]
Element-wise addition:
[[15 10 10 16]
 [15 19  4 12]
 [13  6  8 12]]
Element-wise subtraction:
[[-3  8  0 -4]
 [ 5 -1  2  8]
 [-5  0 -6 -4]]
Element-wise multiplication:
[[54  9 25 60]
 [50 90  3 20]
 [36  9  7 32]]
Element-wise division:
[[0.66666667 9.         1.         0.6       ]
 [2.         0.9        3.         5.        ]
 [0.44444444 1.         0.14285714 0.5       ]]


In [8]:
array = np.arange(1,17).reshape(4,4)
print("Original Array:")
print(array)
print("\n")

row_sum = np.sum(array, axis = 1)
colum_sum = np.sum(array, axis = 0)

print("Row Sum: ")
print(row_sum)

print("Coumn Sum: ")
print(colum_sum)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Row Sum: 
[10 26 42 58]
Coumn Sum: 
[28 32 36 40]


In [14]:
array = np.random.randint(1,25,size = (5,5))
print("Original Array: ")
print(array)
print("\n")


mean = np.mean(array)
median = np.median(array)
std_deviation = np.std(array)
variance = np.var(array)

print("Mean :",mean)
print("Median: ",median)
print("Standard Deviation : ",std_deviation)
print("Variance : ",variance)

Original Array: 
[[22  2 16  2  2]
 [ 5 18  6 21 13]
 [ 2  3 17  1 14]
 [13 16 18  5  9]
 [21  8 23  6 11]]


Mean : 10.96
Median:  11.0
Standard Deviation :  7.1804178151414
Variance :  51.5584


In [17]:
array = np.arange(1,10).reshape(3,3)
print("original array: ")
print(array)
print("\n")

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [21]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("\n")
print("1D array:")
print(row_array)
print("\n")

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[3 3 1]
 [5 6 7]
 [9 3 8]]


1D array:
[ 9 10  4]


Resulting array:
[[12 13  5]
 [14 16 11]
 [18 13 12]]


In [28]:
array = np.random.randint(1,20,size = (4,4))
print("Original Array: ")
print(array)
print("\n")

row_array = np.random.randint(1,20,size=(4,))
print("Row Array:")
print(row_array)
print("\n")

result = array - row_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original Array: 
[[17  7  9 15]
 [ 2  4  4 16]
 [18 19 19  2]
 [ 2 10 14  2]]


Row Array:
[ 1  3  1 11]


Resulting array:
[[16  6  8 14]
 [-1  1  1 13]
 [17 18 18  1]
 [-9 -1  3 -9]]


Ye code NumPy ka use karke ek 4x4 ka random array generate kar raha hai aur ek 1D row array bhi bana raha hai. Phir in dono arrays ka element-wise subtraction ho raha hai. Chalo step-by-step samajhte hain:

### **Step 1: 4x4 ka random array generate karna**
```python
array = np.random.randint(1,20,size = (4,4))
print("Original Array: ")
print(array)
```
- Yeh line ek **4x4 ka matrix** (2D array) banati hai jisme har element 1 se 19 ke beech ka ek random integer hota hai.

### **Step 2: Ek 1D row array generate karna**
```python
row_array = np.random.randint(1,20,size=(4,))
print("Row Array:")
print(row_array)
```
- Yeh ek **1D array (size = 4)** generate karta hai, jo ek row ki tarah behave karega.

### **Step 3: Broadcasting ka use karke subtraction**
```python
result = array - row_array[:, np.newaxis]
print("Resulting array:")
print(result)
```
- `row_array[:, np.newaxis]` ka matlab hai ki hum isko **column vector** bana rahe hain (4x1 shape).
- Ab **broadcasting** ki wajah se yeh column vector **4x4 matrix ke har column se subtract ho jayega**.

### **Example Output:**
Maan lo, ye generated arrays hain:
```
Original Array:
[[10 15  6  8]
 [14  7 19  4]
 [ 5 18 11 12]
 [16 13 17  9]]

Row Array:
[3 8 5 2]

Resulting Array:
[[ 7 12  3  5]  # 10-3, 15-3, 6-3, 8-3
 [ 6 -1 11 -4]  # 14-8, 7-8, 19-8, 4-8
 [ 0 13  6  7]  # 5-5, 18-5, 11-5, 12-5
 [14 11 15  7]] # 16-2, 13-2, 17-2, 9-2
```
### **Key Concept:** **Broadcasting**
- NumPy **automatically adjust karta hai shapes** taki operations perform ho sake.
- `row_array[:, np.newaxis]` (4x1) ko **broadcast** karke (4x4) bana diya gaya.
- Phir **har row ke har element se corresponding row_array ka value minus ho gaya**.

Agar broadcasting na hoti, toh **shapes mismatch ka error** aata! 😅

### `row_array[:, np.newaxis]` ka matlab kya hai? 🤔

#### 🔹 **Problem:**
Jab hum `array - row_array` karte hain, toh **shapes mismatch ho sakti hai** kyunki:
- `array` ka shape **(4,4)** hai.
- `row_array` ka shape **(4,)** hai (yeh ek 1D array hai).

Lekin humein **row-wise subtraction** karna hai **column-wise nahi**, isliye humein `row_array` ka **shape change** karna padega.

---

### 🔹 **`[:, np.newaxis]` ka role**
```python
row_array[:, np.newaxis]
```
- `row_array` ka shape originally `(4,)` hota hai, jo **1D array hai**.
- `[:, np.newaxis]` **iska ek extra dimension add kar deta hai**, taaki yeh **(4,1) ka column vector** ban jaaye.
- Yeh NumPy ka ek **trick hai broadcasting ke liye**, taaki subtraction properly ho sake.

---

### 🔹 **Example with Shapes**
```python
import numpy as np

row_array = np.array([3, 8, 5, 2])
print("Original row_array shape:", row_array.shape)

row_array_new = row_array[:, np.newaxis]
print("New shape after np.newaxis:", row_array_new.shape)
```
🔹 **Output:**
```
Original row_array shape: (4,)
New shape after np.newaxis: (4,1)
```
- Pehle `(4,)` tha (1D array).
- `[:, np.newaxis]` lagane se `(4,1)` ban gaya (2D column vector).

---

### 🔹 **Broadcasting in Action**
Ab agar hum `array` se subtract karein:

```python
array = np.random.randint(1, 20, size=(4,4))
print("Original Array:\n", array)

row_array = np.random.randint(1, 20, size=(4,))
print("\nRow Array:\n", row_array)

result = array - row_array[:, np.newaxis]
print("\nResulting Array:\n", result)
```
🔹 **Explanation:**
- `row_array[:, np.newaxis]` ka shape **(4,1)** ho gaya.
- Ab NumPy isko **(4,4)** me **broadcast** karega, taki subtraction possible ho.
- Har row ke **har column se corresponding row_array ka element minus ho jayega**.

---

### 🔹 **Summary**
- `row_array[:, np.newaxis]` ka use karke **row ko column me convert** kar rahe hain.
- Isse NumPy **broadcasting enable** karta hai, taki subtraction **har row ke sabhi elements pe ho sake**.
- Agar yeh nahi lagate toh `array - row_array` shape mismatch error de sakta tha.

Ab clear hai? 😃

In [29]:
matrix = np.arange(1,10).reshape(3,3)
print("Matrix")
print(matrix)
print("\n")

determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Determinant: -9.51619735392994e-16
Inverse:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


Ye code **NumPy ka linear algebra module (`np.linalg`)** use karke ek matrix ke **determinant, inverse, aur eigenvalues** calculate kar raha hai. Chalo step-by-step samajhte hain:

---

### **1️⃣ Determinant nikalna**
```python
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)
```
🔹 **Explanation:**  
- `np.linalg.det(matrix)` kisi bhi **square matrix ka determinant** nikalta hai.
- Determinant ek **single number hota hai** jo batata hai ki matrix **invertible hai ya nahi**.
- Agar `det = 0` ho, to matrix ka **inverse exist nahi karta**.

✅ **Example:**
```python
matrix = np.array([[4, 3], [2, 1]])
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)
```
🔹 **Output:**
```
Determinant: -2.0
```

---

### **2️⃣ Inverse nikalna**
```python
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)
```
🔹 **Explanation:**  
- `np.linalg.inv(matrix)` kisi bhi **square matrix ka inverse** nikalta hai.
- **Condition:** Matrix **invertible tabhi hoti hai jab uska determinant `0` na ho**.
- Inverse matrix ka matlab hota hai ek aisi matrix jo **original matrix ke saath multiply karne pe identity matrix deti hai**.

✅ **Example:**
```python
matrix = np.array([[4, 3], [2, 1]])
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)
```
🔹 **Output:**
```
Inverse:
[[-0.5  1.5]
 [ 1.  -2. ]]
```
👉 **Check:** Agar `matrix @ inverse` karenge to **identity matrix milega**.

---

### **3️⃣ Eigenvalues nikalna**
```python
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)
```
🔹 **Explanation:**  
- Eigenvalues (`λ`) **kisi matrix ka special property** hoti hain jo **linear transformations** me kaam aati hain.
- `np.linalg.eigvals(matrix)` **sirf eigenvalues** return karega (eigenvectors nahi).
- Eigenvalues ka formula hota hai:
  \[
  \det(A - \lambda I) = 0
  \]
  Jahan `I` **identity matrix** hai aur `λ` eigenvalues hain.

✅ **Example:**
```python
matrix = np.array([[4, 3], [2, 1]])
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)
```
🔹 **Output:**
```
Eigenvalues: [5.61803399 -0.61803399]
```

---

### **Summary**
| Function | Kya Karta Hai? |
|----------|--------------|
| `np.linalg.det(matrix)` | **Determinant** nikalta hai (0 hoga to inverse nahi milega). |
| `np.linalg.inv(matrix)` | **Inverse matrix** return karta hai (agar determinant **zero nahi** hai to). |
| `np.linalg.eigvals(matrix)` | Matrix ki **eigenvalues** return karta hai. |

Matlab agar **matrix ka determinant 0 ho**, to `np.linalg.inv(matrix)` error dega! 😃

In [33]:
array1 = np.random.randint(1,11,size=(2,3))
array2 = np.random.randint(1,11,size=(3,2))

print(array1)
print(array2)
print("\n")

matrix_mul = np.dot(array1,array2)
print("Matrix Multiplied: ")
print(matrix_mul)

[[ 4  6  2]
 [10  2  3]]
[[9 4]
 [8 1]
 [7 7]]


Matrix Multiplied: 
[[ 98  36]
 [127  63]]


In [34]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [35]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[10  1 18 11  8]
 [ 4 16 16 13 20]
 [ 2  4  1 16 10]
 [ 8 15 17 13  7]
 [10 11 15  2  4]]
Flattened array:
[10  1 18 11  8  4 16 16 13 20  2  4  1 16 10  8 15 17 13  7 10 11 15  2
  4]
Reshaped array:
[[10  1 18 11  8]
 [ 4 16 16 13 20]
 [ 2  4  1 16 10]
 [ 8 15 17 13  7]
 [10 11 15  2  4]]


In [36]:
#Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[ 6 16  6 20  7]
 [ 7  8  5  1  7]
 [ 8 16  4  8  9]
 [ 9 19 10 11  9]
 [13  9 16  2  8]]
Corner elements:
[ 6  7 13  8]


In [39]:
array = np.random.randint(1,21,size=(4,4))
print("Original Array; ")
print(array)
print("\n")

array[array>10]=10
print("Modified Array")
print(array)

Original Array; 
[[ 6 11 18 14]
 [ 7  9 20 20]
 [ 2  5 15 16]
 [ 1 13 10 10]]


Modified Array
[[ 6 10 10 10]
 [ 7  9 10 10]
 [ 2  5 10 10]
 [ 1 10 10 10]]


In [41]:
import numpy.ma as ma
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 9 19 13]
 [ 2 11  5]
 [16  4  7]]
Masked array:
[[-- 19 13]
 [2 -- 5]
 [16 4 --]]
Modified masked array:
[[ 9 19 13]
 [ 2  9  5]
 [16  4  9]]


### **📌 Code Breakdown & Explanation**  

Yeh code **NumPy masked arrays** ka use karke **diagonal elements ko mask kar raha hai** aur unko **unmasked elements ke mean se replace kar raha hai**. Chalo ek-ek step samajhte hain.  

---

### **🔹 Step 1: Import Libraries**
```python
import numpy as np
import numpy.ma as ma  # NumPy masked array module
```
✅ **NumPy** import kiya, jo arrays ke operations ke liye hota hai.  
✅ **NumPy masked array (`numpy.ma`)** import kiya, jo array ke kuch elements ko **hide/mask** karne ke liye use hota hai.

---

### **🔹 Step 2: Random 3x3 Array Banaya**
```python
array = np.random.randint(1, 21, size=(3, 3))
```
✅ **Ek random `(3,3)` matrix banaya** jisme har element `1 se 20` ke beech hoga.  

👉 **Example Output:**
```
[[ 4 10 15]
 [20  3 17]
 [ 2 12 18]]
```

---

### **🔹 Step 3: Masked Array Banana (Diagonal Masked)**
```python
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
```
✅ **`np.eye(3, dtype=bool)` ek identity matrix hai** jisme **diagonal elements `True` honge** (matlab mask ho jayenge).  

👉 **Example of `np.eye(3, dtype=bool)`:**
```
[[ True False False]
 [False  True False]
 [False False  True]]
```
✅ **`ma.masked_array()` ka use karke mask apply kiya** jisse **diagonal elements hide ho gaye**.

👉 **Example Masked Array:**
```
[[-- 10 15]
 [20 -- 17]
 [ 2 12 --]]
```
🔹 **Diagonal elements (`4, 3, 18`) hide (`--`) ho gaye!**

---

### **🔹 Step 4: Unmasked Elements ka Mean Calculate Karna**
```python
mean_unmasked = masked_array.mean()
```
✅ **`masked_array.mean()` sirf unmasked (visible) elements ka mean nikalta hai.**  
✅ **Example Calculation:**
```
(10 + 15 + 20 + 17 + 2 + 12) / 6 = 12.66 (approx)
```

---

### **🔹 Step 5: Masked Elements ko Replace Karna**
```python
masked_array = masked_array.filled(mean_unmasked)
```
✅ **`.filled(mean_unmasked)` function** masked elements ko `mean_unmasked` se replace kar dega.  

👉 **Final Output:**
```
[[12.66  10  15]
 [ 20  12.66  17]
 [  2  12  12.66]]
```
🔹 **Jahaan pe mask tha (`--`), wahan mean value insert ho gayi!** 🎯

---

### **🔹 Summary**
| Step | Kya Kiya? |
|------|-----------|
| 1️⃣ | Random `3x3` matrix generate kiya. |
| 2️⃣ | **Diagonal elements ko mask kiya** using `np.eye(3, dtype=bool)`. |
| 3️⃣ | **Unmasked elements ka mean nikal liya**. |
| 4️⃣ | **Masked elements ko us mean se replace kar diya**. |

---

### **📌 Final Thoughts**
✅ **Masked arrays** tab useful hote hain jab hume **kuch elements ko ignore ya replace** karna ho.  
✅ **`np.eye(n, dtype=bool)`** se **diagonal ko mask kar sakte hain**.  
✅ **`masked_array.filled(value)`** se **masked elements ko kisi bhi value se replace kar sakte hain**.  

Ab clear hai? 😃