### Numpy in Python

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
!pip install numpy

In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

### **Array kya hota hai?**
Array ek data structure hai jisme ek hi type ke multiple elements ko ek saath store kiya jaata hai. In elements ko ek fixed size memory block mein store kiya jaata hai, aur aap array ki index positions se elements ko access kar sakte ho.

#### Example:
```python
# Ek simple array:
arr = [1, 2, 3, 4, 5]
```

### **1-Dimensional Array (1D Array)**

1D array ek aise array ko kaha jaata hai jisme elements ek hi row mein arranged hote hain. Isme sirf ek dimension hota hai.

#### Example:
```python
arr = [1, 2, 3, 4, 5]
```
Yeh array ek row mein elements ko store karta hai. Is array mein har element ek index ke through access kiya jaata hai (starting from index 0).

#### Visualization:
```
Index:    0    1    2    3    4
Array:    1    2    3    4    5
```

### **2-Dimensional Array (2D Array)**

2D array ek array hota hai jisme elements ko rows aur columns mein arrange kiya jaata hai. Ismein do dimensions hote hain — ek row dimension aur ek column dimension. Aap soch sakte ho jaise ek matrix.

#### Example:
```python
arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
```
Yeh 2D array 3 rows aur 3 columns mein organize hota hai.

#### Visualization:
```
Row 0:    1    2    3
Row 1:    4    5    6
Row 2:    7    8    9
```

Yeh array rows aur columns ke form mein elements ko store karta hai. Aap index ke zariye specific element ko access kar sakte ho, jaise:
```python
arr[0][2]  # Output: 3
```

### **Summary:**
- **1D Array**: Ek single line mein elements store kiye jaate hain (like a list).
- **2D Array**: Multiple rows aur columns mein elements store kiye jaate hain (like a matrix).

Arrays ka use karne se aapko ek structured way milta hai data ko store aur access karne ka, aur aap easily specific elements ko retrieve kar sakte ho.

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
##Numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#addition
print("Addition:", arr1+arr2)

#Subtraction
print("Subtraction:", arr1-arr2)

#Multiplication
print("Multiplication:", arr1*arr2)

#Division
print("Division:", arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [18]:
#universal function

arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [21]:
# array slicing and indexing
arr = np.array(([1,2,3,4],[3,4,5,6],[6,7,8,9]))
print("Array \n", arr)

Array 
 [[1 2 3 4]
 [3 4 5 6]
 [6 7 8 9]]


In [22]:
arr[0][3]

4

In [30]:
arr[1:,0:2]

array([[3, 4],
       [6, 7]])

In [32]:
#modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  3   4   5   6]
 [  6   7   8   9]]


In [37]:
## statistical operations - normalization

# to have a meanof 0 and a standard deviation as 1

data = np.array([1 , 2 , 3 , 4 , 5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean)/std_dev
print("Normalized data", normalized_data)
print(mean)
print(std_dev)


Normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.0
1.4142135623730951


In [38]:
x = np.array([1,2,3,4,5,6,7,8,9])

mean = np.mean(x)
print(mean)

median = np.median(x)
print(median)

std_devx = np.std(x)
print(std_devx)

variance = np.var(x)
print(variance)

5.0
5.0
2.581988897471611
6.666666666666667


In [39]:
x = np.array([1,2,3,4,5,6,7,8,9])
x[x>5]

array([6, 7, 8, 9])